version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/data:/usr/src/app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=change_me
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
